# Generated by Django 4.2.1 on 2023-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
